server:
  host: localhost
  port: 9000
  mode: debug
  readTimeout: 60s
  writeTimeout: 60s

token:
  method: HS256
  key: followyourheartenjoyyourlifeeverythingwillbefine
  issuer: GLI Tech

db:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: root
  name: pump
redis:
  host: localhost
  port: 6379