version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - test-net

    volumes:
      - redis-data:/data
  pg:
    image: postgres
    restart: always
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - test-net
    volumes:
      - db:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

networks:
  test-net:
volumes:
  db:
  redis-data:
