version: "3.3"

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik.yml:/etc/traefik/traefik.yml:ro"
      - "dynamic.yml:/etc/traefik/dynamic.yml:ro"
    networks:
      - traefik-net
  server:
    image: "server:server-version"
    container_name: "server"
    depends_on:
      - redis
      - pg
    expose:
      - 9000
    labels:
      - "traefik.enable=true"

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    labels:
      - "traefik.enable=true"
    volumes:
      - redis-data:/data
  pg:
    image: postgres
    restart: always
    container_name: pg
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    labels:
      - "traefik.enable=true"
    volumes:
      - db:/var/lib/postgresql/data
      - dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

networks:
  traefik-net:
volumes:
  db:
  redis-data:
