version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"

    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=60
      - --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=60
      - --entryPoints.redis.address=:6379
      - --entryPoints.mysql.address=:3306

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  server:
    image: "server:latest"
    container_name: "server"
    expose:
      - 9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.localhost`)"
      - "traefik.http.routers.redis.entrypoints=web"
