################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: DEBUG

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #   middlewares:
    #     - auth@file
    #     - strip@file
  websecure:
    address: ":443"
    # http:
    #   middlewares:
    #     - auth@file
    #     - strip@file
  mysql:
    address: ":3306"
