name: Deploy To Ali
on:
  push:
    tags:
      - "v*"
jobs:
  PushToAliCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Aliyun Container
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: "${{secrets.REGISTRY_USERNAME}}"
          password: "${{secrets.REGISTRY_PASSWORD}}"
      - name: Build Container
        run: make container
      - name: Push Docker Image
        run: make push-ali
      - name: Copy Scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "scripts/docker-compose.yml"
          target: "."
      - name: Pull Dokcer Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull registry.cn-shanghai.aliyuncs.com/${{ secrets.REPOSITORY_NAME }}:${{ env.RELEASE_VERSION }}
            